-- Database script was generated by Core Lab MySQL Developer
-- Script date 14.06.2018 13:55:24
-- MySQL server version: 5.0.27-community-nt
-- MySQL client version: 4.1
-- ---------------------------------------------------------------------- 
-- Server: localhost
-- Port: 3306
-- Database: internetshop

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Database internetshop structure
-- 

USE mysql;

DROP DATABASE IF EXISTS internetshop;
CREATE DATABASE internetshop;

USE internetshop;

-- 
-- Table structure for table allgoods
-- 
CREATE TABLE `allgoods` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(2000) character set utf8 default NULL,
  `price` double default NULL,
  `count` int(11) default NULL,
  `img1` varchar(2000) character set utf8 default NULL,
  `img2` varchar(2000) character set utf8 default NULL,
  `img3` varchar(2000) character set utf8 default NULL,
  `img4` varchar(2000) character set utf8 default NULL,
  `img5` varchar(2000) character set utf8 default NULL,
  `img6` varchar(2000) character set utf8 default NULL,
  `groupGoods` varchar(50) character set utf8 default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- 
-- Table structure for table users
-- 
CREATE TABLE `users` (
  `id` int(11) NOT NULL auto_increment,
  `login` varchar(20) character set utf8 default NULL,
  `password` varchar(20) character set utf8 default NULL,
  `email` varchar(20) character set utf8 default NULL,
  `gender` varchar(20) character set utf8 default NULL,
  `year` int(11) default NULL,
  `day` int(11) default NULL,
  `month` varchar(20) character set utf8 default NULL,
  `name` varchar(20) default NULL,
  `surename` varchar(20) default NULL,
  `role` varchar(20) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- 
-- Dumping data for table allgoods
-- 
LOCK TABLES allgoods WRITE;
INSERT INTO allgoods VALUES (1, 'CyberpowerPC Gamer Ultra GUA3400A Gaming Desktop', 1400, 210, '../../Img/Goods/Desktops/CyberpowerPCGamerUltra/CyberpowerPCGamerUltra_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (2, 'CYBERPOWERPC Gamer Xtreme GXIVR8020A4 Desktop Gaming PC', 781, 200, '../../Img/Goods/Desktops/CYBERPOWERPCGamerXtreme/CYBERPOWERPCGamerXtreme_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (3, 'HP Pavilion Power Gaming PC', 1050, 200, '../../Img/Goods/Desktops/HPPavilionPowerGamingDesktop/HPPavilionPowerGaming_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (4, 'iBUYPOWER Gaming PC ', 1549, 200, '../../Img/Goods/Desktops/iBUYPOWERGamingPC/iBUYPOWERGamingPC_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (5, 'SkyTech ArchAngel', 699, 200, '../../Img/Goods/Desktops/SkyTechArchAngel/SkyTech ArchAngel_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (6, 'SkyTech Omega Gaming Computer Desktop PC ', 1799, 200, '../../Img/Goods/Desktops/SkyTechOmegaGamingComputerDesktopPC/SkyTechOmegaGamingComputerDesktopPC_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (7, 'Corsair CS-9000009-NA ONE PRO Compact Gaming Desktop PC', 2549, 200, '../../Img/Goods/Desktops/CorsairCS-9000009-NAONEPROCompactGamingDesktopPC/CorsairCS-9000009-NAONEPROCompactGamingDesktopPC_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (8, 'ZOTAC GAMING MEK1 GAMING PC', 1599, 200, '../../Img/Goods/Desktops/ZOTACGAMINGMEK1GAMINGPC/ZOTACGAMINGMEK1GAMINGPC_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (9, 'OMEN by HP Gaming Desktop Computer', 2427, 200, '../../Img/Goods/Desktops/OMENbyHPGamingDesktopComputer/OMENbyHPGamingDesktopComputer_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (10, 'CYBERPOWERPC Gamer Master GMA6400CPG Gaming PC', 2103, 200, '../../Img/Goods/Desktops/CYBERPOWERPCGamerMasterGMA6400CPGGamingPC/CYBERPOWERPCGamerMasterGMA6400CPGGamingPC_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (11, 'CYBERPOWERPC Gamer Master GMA2600A Desktop Gaming PC', 669, 200, '../../Img/Goods/Desktops/CYBERPOWERPCGamerMasterGMA2600ADesktopGamingPC/CYBERPOWERPCGamerMasterGMA2600ADesktopGamingPC_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Desktop');
INSERT INTO allgoods VALUES (12, 'EVGA GeForce GTX 1080 ', 683, 200, '../../Img/Goods/GraphicsCards/EVGA GeForce GTX 1080/EVGA GeForce GTX 1080 SC GAMING ACX 3.0, 8GB GDDR5X_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (13, 'Sapphire Radeon NITRO+ RX 580', 329, 200, '../../Img/Goods/GraphicsCards/Sapphire 112650120G Radeon NITRORX 580/Sapphire 112650120G RadeonNITRO RX 580 8GB GDDR5 DUAL_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (14, 'Sapphire Radeon NITRO RX VEGA 64 8GB ', 415, 200, '../../Img/Goods/GraphicsCards/Sapphire 112750340G Radeon NITRO RX VEGA 64 8GB/Sapphire 112750340G Radeon NITRO RX VEGA 64 8GB HBM2 DUAL HDMIDP (UEFI) PCI-E Graphics Card_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (15, 'ASUS Cerberus GeForce GTX 1050 Ti 4GB', 453, 200, '../../Img/Goods/GraphicsCards/ASUS Cerberus GeForce GTX 1050 Ti 4GB/ASUS Cerberus GeForce GTX 1050 Ti 4GB OC Edition GDDR5_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (16, 'EVGA GeForce GTX 1080 Ti SC Black Edition GAMING', 889, 200, '../../Img/Goods/GraphicsCards/EVGA GeForce GTX 1080 Ti SC Black Edition GAMING/EVGA GeForce GTX 1080 Ti SC Black Edition GAMING_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (17, 'Gigabyte GV-N1030D4-2GL GeForce GT 1030', 99, 200, '../../Img/Goods/GraphicsCards/Gigabyte GeeForce1030/Gigabyte GV-N1030D4-2GL GeForce GT 1030 Low Profile D4 2G_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (18, 'MSI Gaming Radeon RX 580 256-bit 8GB GDRR5', 538, 200, '../../Img/Goods/GraphicsCards/MSI Gaming Radeon RX 580/MSI Gaming Radeon RX 580 256-bit 8GB GDRR5 DirectX 12_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (19, 'ASUS GeForce GTX 1060 6GB Dual-fan', 694, 200, '../../Img/Goods/GraphicsCards/ASUS GeForce GTX 1060 6GB Dual-fan/ASUS GeForce GTX 1060 6GB Dual-fan OC Edition VR Ready Dual HDMI_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (20, 'Gigabyte GeForce GTX 1060 Windforce', 503, 200, '../../Img/Goods/GraphicsCards/Gigabyte GeForce GTX 1060 Windforce/Gigabyte GeForce GTX 1060 Windforce OC 3GB GDDR5 Graphics Card_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (21, 'Gigabyte GeForce GTX 1080', 719, 200, '../../Img/Goods/GraphicsCards/Gigabyte GeForce GTX 1080/Gigabyte GeForce GTX GV-N1080TTOC-8GD Video Graphics Cards_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
INSERT INTO allgoods VALUES (22, 'ASUS ROG Strix Radeon RX 570 O4G', 656, 200, '../../Img/Goods/GraphicsCards/ASUS ROG Strix Radeon RX 570 O4G/ASUS ROG Strix Radeon RX 570 O4G Gaming OC Edition GDDR5_img1.jpg', NULL, NULL, NULL, NULL, NULL, 'Graphics');
UNLOCK TABLES;

-- 
-- Dumping data for table users
-- 
LOCK TABLES users WRITE;
INSERT INTO users VALUES (1, 'Steven', 'Spielberg', 'Spielberg@mail.com', 'Male', 1946, 18, 'December', 'Steven', 'Spielberg', 'user');
INSERT INTO users VALUES (2, 'Christopher', 'Nolan', 'Nolan@mail.com', 'Male', 1970, 30, 'July', 'Christopher', 'Nolan', 'user');
INSERT INTO users VALUES (3, 'Quentin', 'Tarantino', 'Tarantino@mail.com', 'Male', 1963, 27, 'March', 'Quentin', 'Tarantino', 'user');
INSERT INTO users VALUES (4, 'Martin', 'Scorsese', 'Scorsese@mail.com', 'Male', 1942, 17, 'November', 'Martin', 'Scorsese', 'Admin');
INSERT INTO users VALUES (5, 'James', 'Cameron', 'Cameron@mail.com', 'Male', 1954, 16, 'August', 'James', 'Cameron', 'Master');
UNLOCK TABLES;


/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

